/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var r=Object.defineProperty;var d=Object.getOwnPropertyDescriptor;var p=Object.getOwnPropertyNames;var c=Object.prototype.hasOwnProperty;var l=(e,t)=>{for(var s in t)r(e,s,{get:t[s],enumerable:!0})},k=(e,t,s,n)=>{if(t&&typeof t=="object"||typeof t=="function")for(let a of p(t))!c.call(e,a)&&a!==s&&r(e,a,{get:()=>t[a],enumerable:!(n=d(t,a))||n.enumerable});return e};var T=e=>k(r({},"__esModule",{value:!0}),e);var g={};l(g,{default:()=>o});module.exports=T(g);var i=require("obsidian"),o=class extends i.Plugin{async onload(){this.addCommand({id:"insert-fast-task",name:"Insert Fast Task",callback:()=>this.insertTask()}),new i.Notice("\u2705 Fast Tasks Plugin Loaded")}insertTask(){var a;let t=(a=this.app.workspace.getActiveViewOfType(i.MarkdownView))==null?void 0:a.editor;if(!t)return;let s=new Date().toISOString().split("T")[0],n=`- [ ] \u{1F534} **High Priority Task**  
  **Due:** ${s}  
  **Status:** \u23F3 In Progress  
  **Updated:** ${s}  
`;t.replaceSelection(n)}};
